name: "Statuspage — Post NOW (3 maintenances)"

on:
  workflow_dispatch:

jobs:
  unionpay-now:
    uses: ./.github/workflows/reusable-statuspage-maintenance.yml
    with:
      maintenance_name: "银联转账"
      maintenance_body: "【即时维护开始】银联转账正在进行维护（立即开始至本地时间08:00）。"
      component_code: "jb97qs2wnwkk"
      start_local: "23:30"
      end_local: "08:00"
      mode: post_now
      tz_name: "Asia/Kuala_Lumpur"
    secrets: inherit

  local-bank-transfer-now:
    uses: ./.github/workflows/reusable-statuspage-maintenance.yml
    with:
      maintenance_name: "本地银行转账"
      maintenance_body: "【即时维护开始】本地银行转账正在进行维护（立即开始至本地时间09:30）。"
      component_code: "jb97qs2wnwkk"
      start_local: "22:30"
      end_local: "09:30"
      mode: post_now
      tz_name: "Asia/Kuala_Lumpur"
    secrets: inherit

  local-bank-now:
    uses: ./.github/workflows/reusable-statuspage-maintenance.yml
    with:
      maintenance_name: "本地银行"
      maintenance_body: "【即时维护开始】本地银行正在进行维护（立即开始至本地时间08:00）。"
      component_code: "jb97qs2wnwkk"
      start_local: "23:00"
      end_local: "08:00"
      mode: post_now
      tz_name: "Asia/Kuala_Lumpur"
    secrets: inherit
